
/* File generated by gen_cfile.py. Should not be modified. */

#include "motor.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Select_profile = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
REAL32 Profile_data[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x11 */
  {
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000
  };
UNS16 Analog_input_status[] =		/* Mapped at index 0x2313, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Fault_register[] =		/* Mapped at index 0x2320, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Device_status[] =		/* Mapped at index 0x2323, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
REAL32 kpki[] =		/* Mapped at index 0x2331, subindex 0x01 - 0x02 */
  {
    0.000000,
    0.000000
  };
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
UNS32 Profile_acceleration = 0x0;		/* Mapped at index 0x6083, subindex 0x00 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Motor_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Motor_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Motor_iam_a_slave = 0;

TIMER_HANDLE Motor_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Motor_obj1000 = 0x0;	/* 0 */
                    subindex Motor_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Motor_obj1001 = 0x0;	/* 0 */
                    subindex Motor_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Motor_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Motor_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Motor_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Motor_obj1005 = 0x80;	/* 128 */
                    subindex Motor_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Motor_obj1006 = 0x0;	/* 0 */
                    subindex Motor_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 Motor_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Motor_obj100D = 0x0;   /* 0 */

/* index 0x1010 :   Store parameters. */
                    UNS8 Motor_highestSubIndex_obj1010 = 127; /* number of subindex - 1*/
                    UNS32 Motor_obj1010_Save_All_Parameters = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Communication_Parameters = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Application_Parameters = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_1 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_2 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_3 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_4 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_5 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_6 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_7 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_8 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_9 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_10 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_11 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_12 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_13 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_14 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_15 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_16 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_17 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_18 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_19 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_20 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_21 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_22 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_23 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_24 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_25 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_26 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_27 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_28 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_29 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_30 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_31 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_32 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_33 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_34 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_35 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_36 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_37 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_38 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_39 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_40 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_41 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_42 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_43 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_44 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_45 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_46 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_47 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_48 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_49 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_50 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_51 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_52 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_53 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_54 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_55 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_56 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_57 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_58 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_59 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_60 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_61 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_62 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_63 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_64 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_65 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_66 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_67 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_68 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_69 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_70 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_71 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_72 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_73 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_74 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_75 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_76 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_77 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_78 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_79 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_80 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_81 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_82 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_83 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_84 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_85 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_86 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_87 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_88 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_89 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_90 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_91 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_92 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_93 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_94 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_95 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_96 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_97 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_98 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_99 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_100 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_101 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_102 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_103 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_104 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_105 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_106 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_107 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_108 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_109 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_110 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_111 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_112 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_113 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_114 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_115 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_116 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_117 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_118 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_119 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_120 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_121 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_122 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_123 = 0x0;	/* 0 */
                    UNS32 Motor_obj1010_Save_Manufacturer_Parameters_124 = 0x0;	/* 0 */
                    subindex Motor_Index1010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1010, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_All_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Communication_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Application_Parameters, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_1, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_2, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_3, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_4, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_5, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_6, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_7, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_8, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_9, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_10, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_11, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_12, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_13, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_14, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_15, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_16, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_17, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_18, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_19, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_20, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_21, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_22, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_23, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_24, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_25, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_26, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_27, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_28, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_29, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_30, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_31, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_32, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_33, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_34, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_35, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_36, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_37, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_38, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_39, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_40, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_41, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_42, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_43, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_44, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_45, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_46, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_47, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_48, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_49, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_50, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_51, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_52, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_53, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_54, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_55, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_56, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_57, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_58, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_59, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_60, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_61, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_62, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_63, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_64, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_65, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_66, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_67, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_68, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_69, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_70, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_71, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_72, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_73, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_74, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_75, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_76, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_77, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_78, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_79, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_80, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_81, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_82, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_83, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_84, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_85, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_86, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_87, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_88, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_89, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_90, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_91, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_92, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_93, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_94, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_95, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_96, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_97, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_98, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_99, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_100, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_101, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_102, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_103, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_104, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_105, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_106, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_107, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_108, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_109, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_110, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_111, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_112, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_113, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_114, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_115, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_116, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_117, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_118, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_119, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_120, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_121, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_122, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_123, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1010_Save_Manufacturer_Parameters_124, NULL }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Motor_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Motor_highestSubIndex_obj1016 = 0;
                    UNS32 Motor_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Motor_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Motor_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Motor_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Motor_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Motor_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Motor_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Motor_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x600;	/* 1536 */
                    UNS32 Motor_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x580;	/* 1408 */
                    UNS8 Motor_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex Motor_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Motor_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Motor_obj1281_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Motor_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 Motor_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 Motor_obj1282_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex Motor_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1282, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1282_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1282_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1282_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 Motor_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 Motor_obj1283_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex Motor_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1283, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1283_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1283_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1283_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 Motor_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 Motor_obj1284_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex Motor_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1284, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1284_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1284_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1284_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 Motor_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 Motor_obj1285_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex Motor_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1285, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1285_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1285_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1285_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1542 */
                    UNS32 Motor_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1414 */
                    UNS8 Motor_obj1286_Node_ID_of_the_SDO_Server = 0x6;	/* 6 */
                    subindex Motor_Index1286[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1286, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1286_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1286_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1286_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1287 :   Client SDO 8 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1287 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1287_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 Motor_obj1287_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 Motor_obj1287_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex Motor_Index1287[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1287, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1287_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1287_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1287_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1288 :   Client SDO 9 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1288 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1288_COB_ID_Client_to_Server_Transmit_SDO = 0x608;	/* 1544 */
                    UNS32 Motor_obj1288_COB_ID_Server_to_Client_Receive_SDO = 0x588;	/* 1416 */
                    UNS8 Motor_obj1288_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    subindex Motor_Index1288[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1288, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1288_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1288_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1288_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1289 :   Client SDO 10 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1289 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1289_COB_ID_Client_to_Server_Transmit_SDO = 0x609;	/* 1545 */
                    UNS32 Motor_obj1289_COB_ID_Server_to_Client_Receive_SDO = 0x589;	/* 1417 */
                    UNS8 Motor_obj1289_Node_ID_of_the_SDO_Server = 0x9;	/* 9 */
                    subindex Motor_Index1289[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1289, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1289_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1289_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1289_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128A :   Client SDO 11 Parameter. */
                    UNS8 Motor_highestSubIndex_obj128A = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj128A_COB_ID_Client_to_Server_Transmit_SDO = 0x60A;	/* 1546 */
                    UNS32 Motor_obj128A_COB_ID_Server_to_Client_Receive_SDO = 0x58A;	/* 1418 */
                    UNS8 Motor_obj128A_Node_ID_of_the_SDO_Server = 0xA;	/* 10 */
                    subindex Motor_Index128A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj128A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128A_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128A_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj128A_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128B :   Client SDO 12 Parameter. */
                    UNS8 Motor_highestSubIndex_obj128B = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj128B_COB_ID_Client_to_Server_Transmit_SDO = 0x60B;	/* 1547 */
                    UNS32 Motor_obj128B_COB_ID_Server_to_Client_Receive_SDO = 0x58B;	/* 1419 */
                    UNS8 Motor_obj128B_Node_ID_of_the_SDO_Server = 0xB;	/* 11 */
                    subindex Motor_Index128B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj128B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128B_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128B_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj128B_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128C :   Client SDO 13 Parameter. */
                    UNS8 Motor_highestSubIndex_obj128C = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj128C_COB_ID_Client_to_Server_Transmit_SDO = 0x60C;	/* 1548 */
                    UNS32 Motor_obj128C_COB_ID_Server_to_Client_Receive_SDO = 0x58C;	/* 1420 */
                    UNS8 Motor_obj128C_Node_ID_of_the_SDO_Server = 0xC;	/* 12 */
                    subindex Motor_Index128C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj128C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128C_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128C_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj128C_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128D :   Client SDO 14 Parameter. */
                    UNS8 Motor_highestSubIndex_obj128D = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj128D_COB_ID_Client_to_Server_Transmit_SDO = 0x60D;	/* 1549 */
                    UNS32 Motor_obj128D_COB_ID_Server_to_Client_Receive_SDO = 0x58D;	/* 1421 */
                    UNS8 Motor_obj128D_Node_ID_of_the_SDO_Server = 0xD;	/* 13 */
                    subindex Motor_Index128D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj128D, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128D_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128D_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj128D_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128E :   Client SDO 15 Parameter. */
                    UNS8 Motor_highestSubIndex_obj128E = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj128E_COB_ID_Client_to_Server_Transmit_SDO = 0x60E;	/* 1550 */
                    UNS32 Motor_obj128E_COB_ID_Server_to_Client_Receive_SDO = 0x58E;	/* 1422 */
                    UNS8 Motor_obj128E_Node_ID_of_the_SDO_Server = 0xE;	/* 14 */
                    subindex Motor_Index128E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj128E, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128E_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128E_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj128E_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x128F :   Client SDO 16 Parameter. */
                    UNS8 Motor_highestSubIndex_obj128F = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj128F_COB_ID_Client_to_Server_Transmit_SDO = 0x60F;	/* 1551 */
                    UNS32 Motor_obj128F_COB_ID_Server_to_Client_Receive_SDO = 0x58F;	/* 1423 */
                    UNS8 Motor_obj128F_Node_ID_of_the_SDO_Server = 0xF;	/* 15 */
                    subindex Motor_Index128F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj128F, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128F_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj128F_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj128F_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Motor_obj1400_COB_ID_used_by_PDO = 0x206;	/* 518 */
                    UNS8 Motor_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Motor_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 Motor_obj1600[] = 
                    {
                      0x60410010	/* 1614872592 */
                    };
                    subindex Motor_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1600[0], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Motor_obj1800_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 Motor_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Motor_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 Motor_obj1A00[] = 
                    {
                      0x60400010	/* 1614807056 */
                    };
                    subindex Motor_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1A00[0], NULL }
                     };

/* index 0x2000 :   Mapped variable Select profile */
                    subindex Motor_Index2000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Select_profile, NULL }
                     };

/* index 0x2001 :   Mapped variable Profile data */
                    UNS8 Motor_highestSubIndex_obj2001 = 17; /* number of subindex - 1*/
                    subindex Motor_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2001, NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[0], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[1], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[2], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[3], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[4], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[5], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[6], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[7], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[8], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[9], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[10], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[11], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[12], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[13], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[14], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[15], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Profile_data[16], NULL }
                     };

/* index 0x2313 :   Mapped variable Analog input status */
                    UNS8 Motor_highestSubIndex_obj2313 = 4; /* number of subindex - 1*/
                    subindex Motor_Index2313[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2313, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[0], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[1], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[2], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[3], NULL }
                     };

/* index 0x2320 :   Mapped variable Fault register */
                    UNS8 Motor_highestSubIndex_obj2320 = 4; /* number of subindex - 1*/
                    subindex Motor_Index2320[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2320, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[0], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[1], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[2], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[3], NULL }
                     };

/* index 0x2323 :   Mapped variable Device status */
                    UNS8 Motor_highestSubIndex_obj2323 = 4; /* number of subindex - 1*/
                    subindex Motor_Index2323[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2323, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[0], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[1], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[2], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[3], NULL }
                     };

/* index 0x2331 :   Mapped variable kpki */
                    UNS8 Motor_highestSubIndex_obj2331 = 2; /* number of subindex - 1*/
                    subindex Motor_Index2331[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2331, NULL },
                       { RW, real32, sizeof (REAL32), (void*)&kpki[0], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&kpki[1], NULL }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex Motor_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword, NULL }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex Motor_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword, NULL }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex Motor_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value, NULL }
                     };

/* index 0x6078 :   Mapped variable Current actual value */
                    subindex Motor_Index6078[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value, NULL }
                     };

/* index 0x6083 :   Mapped variable Profile acceleration */
                    subindex Motor_Index6083[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_acceleration, NULL }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex Motor_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Motor_objdict[] = 
{
  { (subindex*)Motor_Index1000,sizeof(Motor_Index1000)/sizeof(Motor_Index1000[0]), 0x1000},
  { (subindex*)Motor_Index1001,sizeof(Motor_Index1001)/sizeof(Motor_Index1001[0]), 0x1001},
  { (subindex*)Motor_Index1005,sizeof(Motor_Index1005)/sizeof(Motor_Index1005[0]), 0x1005},
  { (subindex*)Motor_Index1006,sizeof(Motor_Index1006)/sizeof(Motor_Index1006[0]), 0x1006},
  { (subindex*)Motor_Index1010,sizeof(Motor_Index1010)/sizeof(Motor_Index1010[0]), 0x1010},
  { (subindex*)Motor_Index1018,sizeof(Motor_Index1018)/sizeof(Motor_Index1018[0]), 0x1018},
  { (subindex*)Motor_Index1280,sizeof(Motor_Index1280)/sizeof(Motor_Index1280[0]), 0x1280},
  { (subindex*)Motor_Index1281,sizeof(Motor_Index1281)/sizeof(Motor_Index1281[0]), 0x1281},
  { (subindex*)Motor_Index1282,sizeof(Motor_Index1282)/sizeof(Motor_Index1282[0]), 0x1282},
  { (subindex*)Motor_Index1283,sizeof(Motor_Index1283)/sizeof(Motor_Index1283[0]), 0x1283},
  { (subindex*)Motor_Index1284,sizeof(Motor_Index1284)/sizeof(Motor_Index1284[0]), 0x1284},
  { (subindex*)Motor_Index1285,sizeof(Motor_Index1285)/sizeof(Motor_Index1285[0]), 0x1285},
  { (subindex*)Motor_Index1286,sizeof(Motor_Index1286)/sizeof(Motor_Index1286[0]), 0x1286},
  { (subindex*)Motor_Index1287,sizeof(Motor_Index1287)/sizeof(Motor_Index1287[0]), 0x1287},
  { (subindex*)Motor_Index1288,sizeof(Motor_Index1288)/sizeof(Motor_Index1288[0]), 0x1288},
  { (subindex*)Motor_Index1289,sizeof(Motor_Index1289)/sizeof(Motor_Index1289[0]), 0x1289},
  { (subindex*)Motor_Index128A,sizeof(Motor_Index128A)/sizeof(Motor_Index128A[0]), 0x128A},
  { (subindex*)Motor_Index128B,sizeof(Motor_Index128B)/sizeof(Motor_Index128B[0]), 0x128B},
  { (subindex*)Motor_Index128C,sizeof(Motor_Index128C)/sizeof(Motor_Index128C[0]), 0x128C},
  { (subindex*)Motor_Index128D,sizeof(Motor_Index128D)/sizeof(Motor_Index128D[0]), 0x128D},
  { (subindex*)Motor_Index128E,sizeof(Motor_Index128E)/sizeof(Motor_Index128E[0]), 0x128E},
  { (subindex*)Motor_Index128F,sizeof(Motor_Index128F)/sizeof(Motor_Index128F[0]), 0x128F},
  { (subindex*)Motor_Index1400,sizeof(Motor_Index1400)/sizeof(Motor_Index1400[0]), 0x1400},
  { (subindex*)Motor_Index1600,sizeof(Motor_Index1600)/sizeof(Motor_Index1600[0]), 0x1600},
  { (subindex*)Motor_Index1800,sizeof(Motor_Index1800)/sizeof(Motor_Index1800[0]), 0x1800},
  { (subindex*)Motor_Index1A00,sizeof(Motor_Index1A00)/sizeof(Motor_Index1A00[0]), 0x1A00},
  { (subindex*)Motor_Index2000,sizeof(Motor_Index2000)/sizeof(Motor_Index2000[0]), 0x2000},
  { (subindex*)Motor_Index2001,sizeof(Motor_Index2001)/sizeof(Motor_Index2001[0]), 0x2001},
  { (subindex*)Motor_Index2313,sizeof(Motor_Index2313)/sizeof(Motor_Index2313[0]), 0x2313},
  { (subindex*)Motor_Index2320,sizeof(Motor_Index2320)/sizeof(Motor_Index2320[0]), 0x2320},
  { (subindex*)Motor_Index2323,sizeof(Motor_Index2323)/sizeof(Motor_Index2323[0]), 0x2323},
  { (subindex*)Motor_Index2331,sizeof(Motor_Index2331)/sizeof(Motor_Index2331[0]), 0x2331},
  { (subindex*)Motor_Index6040,sizeof(Motor_Index6040)/sizeof(Motor_Index6040[0]), 0x6040},
  { (subindex*)Motor_Index6041,sizeof(Motor_Index6041)/sizeof(Motor_Index6041[0]), 0x6041},
  { (subindex*)Motor_Index606C,sizeof(Motor_Index606C)/sizeof(Motor_Index606C[0]), 0x606C},
  { (subindex*)Motor_Index6078,sizeof(Motor_Index6078)/sizeof(Motor_Index6078[0]), 0x6078},
  { (subindex*)Motor_Index6083,sizeof(Motor_Index6083)/sizeof(Motor_Index6083[0]), 0x6083},
  { (subindex*)Motor_Index60FF,sizeof(Motor_Index60FF)/sizeof(Motor_Index60FF[0]), 0x60FF},
};

const indextable * Motor_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1010: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1281: i = 7;break;
		case 0x1282: i = 8;break;
		case 0x1283: i = 9;break;
		case 0x1284: i = 10;break;
		case 0x1285: i = 11;break;
		case 0x1286: i = 12;break;
		case 0x1287: i = 13;break;
		case 0x1288: i = 14;break;
		case 0x1289: i = 15;break;
		case 0x128A: i = 16;break;
		case 0x128B: i = 17;break;
		case 0x128C: i = 18;break;
		case 0x128D: i = 19;break;
		case 0x128E: i = 20;break;
		case 0x128F: i = 21;break;
		case 0x1400: i = 22;break;
		case 0x1600: i = 23;break;
		case 0x1800: i = 24;break;
		case 0x1A00: i = 25;break;
		case 0x2000: i = 26;break;
		case 0x2001: i = 27;break;
		case 0x2313: i = 28;break;
		case 0x2320: i = 29;break;
		case 0x2323: i = 30;break;
		case 0x2331: i = 31;break;
		case 0x6040: i = 32;break;
		case 0x6041: i = 33;break;
		case 0x606C: i = 34;break;
		case 0x6078: i = 35;break;
		case 0x6083: i = 36;break;
		case 0x60FF: i = 37;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Motor_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Motor_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index Motor_firstIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  22, /* PDO_RCV */
  23, /* PDO_RCV_MAP */
  24, /* PDO_TRS */
  25 /* PDO_TRS_MAP */
};

const quick_index Motor_lastIndex = {
  0, /* SDO_SVR */
  21, /* SDO_CLT */
  22, /* PDO_RCV */
  23, /* PDO_RCV_MAP */
  24, /* PDO_TRS */
  25 /* PDO_TRS_MAP */
};

const UNS16 Motor_ObjdictSize = sizeof(Motor_objdict)/sizeof(Motor_objdict[0]); 

CO_Data Motor_Data = CANOPEN_NODE_DATA_INITIALIZER(Motor);

