
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MOTOR_H
#define MOTOR_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Motor_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Motor_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Motor_Data;
extern UNS16 Analog_input_status[4];		/* Mapped at index 0x2313, subindex 0x01 - 0x04 */
extern UNS16 Fault_register[4];		/* Mapped at index 0x2320, subindex 0x01 - 0x04 */
extern UNS16 Device_status[4];		/* Mapped at index 0x2323, subindex 0x01 - 0x04 */
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/
extern INTEGER16 Current_actual_value;		/* Mapped at index 0x6078, subindex 0x00*/
extern UNS32 Acceleration; /* Mapped at index 0x60C5, subindex 0x00*/
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/

#endif // MOTOR_H
