
/* File generated by gen_cfile.py. Should not be modified. */

#include "motor.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Analog_input_status[] =		/* Mapped at index 0x2313, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Fault_register[] =		/* Mapped at index 0x2320, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Device_status[] =		/* Mapped at index 0x2323, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
UNS32 Acceleration = 0x0; /* Mapped at index 0x60C5, subindex 0x00*/
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Motor_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Motor_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Motor_iam_a_slave = 0;

TIMER_HANDLE Motor_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Motor_obj1000 = 0x0;	/* 0 */
                    subindex Motor_Index1000[] =
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Motor_obj1001 = 0x0;	/* 0 */
                    subindex Motor_Index1001[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Motor_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Motor_obj1003[] =
                    {
                      0x0	/* 0 */
                    };
                    subindex Motor_Index1003[] =
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Motor_obj1005 = 0x80;	/* 128 */
                    subindex Motor_Index1005[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Motor_obj1006 = 0x0;	/* 0 */
                    subindex Motor_Index1006[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */
                    UNS16 Motor_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */
                    UNS8 Motor_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Motor_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Motor_highestSubIndex_obj1016 = 0;
                    UNS32 Motor_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */
                    UNS16 Motor_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Motor_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Motor_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Motor_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Motor_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Motor_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Motor_Index1018[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Motor_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x600;	/* 1536 */
                    UNS32 Motor_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x580;	/* 1408 */
                    UNS8 Motor_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex Motor_Index1280[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Motor_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Motor_obj1281_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Motor_Index1281[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 Motor_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 Motor_obj1282_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex Motor_Index1282[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1282, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1282_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1282_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1282_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 Motor_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 Motor_obj1283_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex Motor_Index1283[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1283, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1283_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1283_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1283_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x604;	/* 1540 */
                    UNS32 Motor_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x584;	/* 1412 */
                    UNS8 Motor_obj1284_Node_ID_of_the_SDO_Server = 0x4;	/* 4 */
                    subindex Motor_Index1284[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1284, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1284_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1284_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1284_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 Motor_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 Motor_obj1285_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex Motor_Index1285[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1285, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1285_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1285_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1285_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1286 :   Client SDO 7 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1286 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1286_COB_ID_Client_to_Server_Transmit_SDO = 0x606;	/* 1542 */
                    UNS32 Motor_obj1286_COB_ID_Server_to_Client_Receive_SDO = 0x586;	/* 1414 */
                    UNS8 Motor_obj1286_Node_ID_of_the_SDO_Server = 0x6;	/* 6 */
                    subindex Motor_Index1286[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1286, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1286_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1286_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1286_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1287 :   Client SDO 8 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1287 = 3; /* number of subindex - 1*/
                    UNS32 Motor_obj1287_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 Motor_obj1287_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 Motor_obj1287_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex Motor_Index1287[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1287, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1287_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1287_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1287_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Motor_obj1400_COB_ID_used_by_PDO = 0x206;	/* 518 */
                    UNS8 Motor_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Index1400[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Motor_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 Motor_obj1600[] =
                    {
                      0x60410010	/* 1614872592 */
                    };
                    subindex Motor_Index1600[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1600[0], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Motor_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Motor_obj1800_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 Motor_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Motor_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Motor_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Motor_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Motor_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Motor_Index1800[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Motor_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 Motor_obj1A00[] =
                    {
                      0x60400010	/* 1614807056 */
                    };
                    subindex Motor_Index1A00[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_obj1A00[0], NULL }
                     };

/* index 0x2313 :   Mapped variable Analog input status */
                    UNS8 Motor_highestSubIndex_obj2313 = 4; /* number of subindex - 1*/
                    subindex Motor_Index2313[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2313, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[0], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[1], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[2], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Analog_input_status[3], NULL }
                     };

/* index 0x2320 :   Mapped variable Fault register */
                    UNS8 Motor_highestSubIndex_obj2320 = 4; /* number of subindex - 1*/
                    subindex Motor_Index2320[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2320, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[0], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[1], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[2], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Fault_register[3], NULL }
                     };

/* index 0x2323 :   Mapped variable Device status */
                    UNS8 Motor_highestSubIndex_obj2323 = 4; /* number of subindex - 1*/
                    subindex Motor_Index2323[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Motor_highestSubIndex_obj2323, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[0], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[1], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[2], NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Device_status[3], NULL }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex Motor_Index6040[] =
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword, NULL }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex Motor_Index6041[] =
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword, NULL }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex Motor_Index606C[] =
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value, NULL }
                     };

/* index 0x6078 :   Mapped variable Current actual value */
                    subindex Motor_Index6078[] =
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value, NULL }
                     };
/* index 0x60C5 :   Mapped variable Acceleration */
                    subindex Motor_Index60C5[] =
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Acceleration, NULL }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex Motor_Index60FF[] =
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Motor_objdict[] =
{
  { (subindex*)Motor_Index1000,sizeof(Motor_Index1000)/sizeof(Motor_Index1000[0]), 0x1000},
  { (subindex*)Motor_Index1001,sizeof(Motor_Index1001)/sizeof(Motor_Index1001[0]), 0x1001},
  { (subindex*)Motor_Index1005,sizeof(Motor_Index1005)/sizeof(Motor_Index1005[0]), 0x1005},
  { (subindex*)Motor_Index1006,sizeof(Motor_Index1006)/sizeof(Motor_Index1006[0]), 0x1006},
  { (subindex*)Motor_Index1018,sizeof(Motor_Index1018)/sizeof(Motor_Index1018[0]), 0x1018},
  { (subindex*)Motor_Index1280,sizeof(Motor_Index1280)/sizeof(Motor_Index1280[0]), 0x1280},
  { (subindex*)Motor_Index1281,sizeof(Motor_Index1281)/sizeof(Motor_Index1281[0]), 0x1281},
  { (subindex*)Motor_Index1282,sizeof(Motor_Index1282)/sizeof(Motor_Index1282[0]), 0x1282},
  { (subindex*)Motor_Index1283,sizeof(Motor_Index1283)/sizeof(Motor_Index1283[0]), 0x1283},
  { (subindex*)Motor_Index1284,sizeof(Motor_Index1284)/sizeof(Motor_Index1284[0]), 0x1284},
  { (subindex*)Motor_Index1285,sizeof(Motor_Index1285)/sizeof(Motor_Index1285[0]), 0x1285},
  { (subindex*)Motor_Index1286,sizeof(Motor_Index1286)/sizeof(Motor_Index1286[0]), 0x1286},
  { (subindex*)Motor_Index1287,sizeof(Motor_Index1287)/sizeof(Motor_Index1287[0]), 0x1287},
  { (subindex*)Motor_Index1400,sizeof(Motor_Index1400)/sizeof(Motor_Index1400[0]), 0x1400},
  { (subindex*)Motor_Index1600,sizeof(Motor_Index1600)/sizeof(Motor_Index1600[0]), 0x1600},
  { (subindex*)Motor_Index1800,sizeof(Motor_Index1800)/sizeof(Motor_Index1800[0]), 0x1800},
  { (subindex*)Motor_Index1A00,sizeof(Motor_Index1A00)/sizeof(Motor_Index1A00[0]), 0x1A00},
  { (subindex*)Motor_Index2313,sizeof(Motor_Index2313)/sizeof(Motor_Index2313[0]), 0x2313},
  { (subindex*)Motor_Index2320,sizeof(Motor_Index2320)/sizeof(Motor_Index2320[0]), 0x2320},
  { (subindex*)Motor_Index2323,sizeof(Motor_Index2323)/sizeof(Motor_Index2323[0]), 0x2323},
  { (subindex*)Motor_Index6040,sizeof(Motor_Index6040)/sizeof(Motor_Index6040[0]), 0x6040},
  { (subindex*)Motor_Index6041,sizeof(Motor_Index6041)/sizeof(Motor_Index6041[0]), 0x6041},
  { (subindex*)Motor_Index606C,sizeof(Motor_Index606C)/sizeof(Motor_Index606C[0]), 0x606C},
  { (subindex*)Motor_Index6078,sizeof(Motor_Index6078)/sizeof(Motor_Index6078[0]), 0x6078},
  { (subindex*)Motor_Index60C5,sizeof(Motor_Index60C5)/sizeof(Motor_Index60C5[0]), 0x60C5},
  { (subindex*)Motor_Index60FF,sizeof(Motor_Index60FF)/sizeof(Motor_Index60FF[0]), 0x60FF},
};

const indextable * Motor_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1018: i = 4;break;
		case 0x1280: i = 5;break;
		case 0x1281: i = 6;break;
		case 0x1282: i = 7;break;
		case 0x1283: i = 8;break;
		case 0x1284: i = 9;break;
		case 0x1285: i = 10;break;
		case 0x1286: i = 11;break;
		case 0x1287: i = 12;break;
		case 0x1400: i = 13;break;
		case 0x1600: i = 14;break;
		case 0x1800: i = 15;break;
		case 0x1A00: i = 16;break;
		case 0x2313: i = 17;break;
		case 0x2320: i = 18;break;
		case 0x2323: i = 19;break;
		case 0x6040: i = 20;break;
		case 0x6041: i = 21;break;
		case 0x606C: i = 22;break;
		case 0x6078: i = 23;break;
        case 0x60C5: i = 24;break;
		case 0x60FF: i = 25;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Motor_objdict[i];
}

/*
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Motor_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index Motor_firstIndex = {
  0, /* SDO_SVR */
  5, /* SDO_CLT */
  13, /* PDO_RCV */
  14, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  16 /* PDO_TRS_MAP */
};

const quick_index Motor_lastIndex = {
  0, /* SDO_SVR */
  12, /* SDO_CLT */
  13, /* PDO_RCV */
  14, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  16 /* PDO_TRS_MAP */
};

const UNS16 Motor_ObjdictSize = sizeof(Motor_objdict)/sizeof(Motor_objdict[0]);

CO_Data Motor_Data = CANOPEN_NODE_DATA_INITIALIZER(Motor);
